CREATE TABLE [dbo].[ToDo]
(
	[Id] INT NOT NULL IDENTITY, 
    [Title] NVARCHAR(128) NOT NULL, 
    [Done] BIT NOT NULL CONSTRAINT DF_ToDo_Done DEFAULT (0), 
    [Created] DATETIME2(7) NOT NULL CONSTRAINT DF_ToDo_Created DEFAULT (SYSDATETIME()), 
    [UserId] INT NOT NULL, 
    CONSTRAINT [PK_ToDo] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_ToDo_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
